# Generated by Django 3.0.8 on 2020-07-07 00:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('id_card', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('birth', models.DateField()),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
