# Generated by Django 3.0.8 on 2020-07-10 20:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0003_auto_20200709_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='This is a field specify that date that of the block was created'),
        ),
        migrations.AlterField(
            model_name='block',
            name='name',
            field=models.CharField(help_text='This is a field for the block name', max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='This is a field specify that date that of the employee was created'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='home_address',
            field=models.CharField(help_text='This is a field for the ubication where the employee lives', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='person_id',
            field=models.ForeignKey(help_text='This is a field for the person number of the employee', on_delete=django.db.models.deletion.CASCADE, to='neighborhood.Person'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(help_text='This is a field for the number of the employee', max_length=10),
        ),
        migrations.AlterField(
            model_name='house',
            name='block_id',
            field=models.ForeignKey(help_text='This is a field for block that contains the house', on_delete=django.db.models.deletion.CASCADE, to='neighborhood.Block'),
        ),
        migrations.AlterField(
            model_name='house',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='This is a field specify that date that of the house was created'),
        ),
        migrations.AlterField(
            model_name='house',
            name='phone',
            field=models.CharField(help_text='This is a field for the house phone', max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth',
            field=models.DateField(help_text='This is a field for the date that was born'),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='This is a field specify that date that of the person was created'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(default=' ', help_text='This is a field for person email', max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='id_card',
            field=models.CharField(help_text='This is field for the numbre of identification card', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(help_text='This is a field for the person name', max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='password',
            field=models.CharField(default=' ', help_text='This is a field for person password', max_length=12),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.BooleanField(help_text='This is a field for the status of the person'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='This is a field specify that date that of the resident was created'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='house_id',
            field=models.ForeignKey(help_text='This is a field for the house number where the resident lives', on_delete=django.db.models.deletion.CASCADE, to='neighborhood.House'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='landlord',
            field=models.BooleanField(help_text='This is a field that identifies if the resident owns the home'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='person_id',
            field=models.ForeignKey(help_text='This is a field for the person number', on_delete=django.db.models.deletion.CASCADE, to='neighborhood.Person'),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='This is a field specify that date that of the role was created'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(help_text='This is a field for the house phone', max_length=100),
        ),
        migrations.AlterField(
            model_name='role_employee',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='This is a field specify date that of the relation between the role and employee was created'),
        ),
        migrations.AlterField(
            model_name='role_employee',
            name='employee_id',
            field=models.ForeignKey(help_text='This is a field for the employee number', on_delete=django.db.models.deletion.CASCADE, to='neighborhood.Employee'),
        ),
        migrations.AlterField(
            model_name='role_employee',
            name='role_id',
            field=models.ForeignKey(help_text='This is a field for the role number', on_delete=django.db.models.deletion.CASCADE, to='neighborhood.Role'),
        ),
    ]
