name: Django CI

on:
  push:
    on: [push]
  pull_request:
    on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pip install prospector
        pipenv install
    - name: Run Lint
      run: |
        pipenv run prospector
    - name: Run Tests
      run: |
        pipenv run python manage.py test

